static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 6380
    filter_chains:
    - filters:
      - name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: redis_stats
          settings:
            op_timeout: 10s
            enable_redirection: true
            enable_hashtagging: true
            enable_command_stats: true
            dns_cache_config:
              name: redis_dns_cache
              dns_lookup_family: V4_ONLY
          prefix_routes:
            routes:
            - prefix: ""
              cluster: redis_cluster
              # 允许所有命令类型
              request_mirror_policy: []
            catch_all_route:
              cluster: redis_cluster

  clusters:
  - name: redis_cluster
    connect_timeout: 4s
    # lb_policy: RING_HASH
    # 修复 multi-exec 命令无法执行的问题
    # https://github.com/envoyproxy/envoy/issues/23651
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.redis
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.redis.v3.RedisClusterConfig
        cluster_refresh_rate: 5s
        cluster_refresh_timeout: 3s
        redirect_refresh_interval: 5s
        redirect_refresh_threshold: 5
        failure_refresh_threshold: 3
        host_degraded_refresh_threshold: 2
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: redis-cluster
                port_value: 6380
        - endpoint:
            address:
              socket_address:
                address: redis-cluster
                port_value: 6381
        - endpoint:
            address:
              socket_address:
                address: redis-cluster
                port_value: 6382
    health_checks:
    - timeout: 3s
      interval: 10s
      unhealthy_threshold: 2
      healthy_threshold: 2
      custom_health_check:
        name: envoy.health_checkers.redis
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.health_checkers.redis.v3.Redis
          key: "__health_check__"

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
